version: '3.9'

services:
  mysql_db:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: TenderDB
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql_db
    ports:
      - "5000:5000"
    command: /wait-for-it.sh mysql_db yourpassword -- dotnet run --project ./TenderManagementAPI.csproj

volumes:
  mysql_data: